const lojas = [
  {
    nome: 'Jogos e Cia - Acre',
    cep: '69918703',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Tabuleirando - Acre',
    cep: '69911204',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Casa dos Meeples - Alagoas',
    cep: '57010-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Desafios e Dados - Alagoas',
    cep: '57020-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Estratégia Central - Amapá',
    cep: '68903-193',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'A Toca dos Tabuleiros - Amapá',
    cep: '68908-290',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Épicos & Desafios - Amazonas',
    cep: '69097224',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Tabuleiro da Amazônia - Amazonas',
    cep: '69087470',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Mundo dos Jogos - Bahia',
    cep: '40010-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Tabuleiros da Bahia - Bahia',
    cep: '40020-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Jogo e Magia - Ceará',
    cep: '60010-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Reino dos Dados - Ceará',
    cep: '60020-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Lúdico - Distrito Federal',
    cep: '72620201',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Distrito dos Meeples - Distrito Federal',
    cep: '72261049',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Pioneiros do Jogo - Espírito Santo',
    cep: '29148425',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Espaço dos Desafios - Espírito Santo',
    cep: '29126710',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Jogos & Estratégias - Goiás',
    cep: '74423377',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Goiás do Tabuleiro - Goiás',
    cep: '74430120',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'O Covil dos Meeples - Maranhão',
    cep: '65068647',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Estratégias Maranhenses - Maranhão',
    cep: '65631640',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Mestre dos Jogos - Mato Grosso',
    cep: '78714228',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Tabuleiros Pantaneiros - Mato Grosso',
    cep: '78705266',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Aventura em Tabuleiros - Mato Grosso do Sul',
    cep: '79011220',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Estratégia e Desafios - Mato Grosso do Sul',
    cep: '79011541',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Império dos Meeples - Minas Gerais',
    cep: '32675614',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Tabuleiros Mineiros - Minas Gerais',
    cep: '35058-270',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Conquistadores do Jogo - Pará',
    cep: '66815-450',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Tabuleiro Amazônico - Pará',
    cep: '66010-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Meeples Paraibanos - Paraíba',
    cep: '58080490',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Tabuleiro & Companhia - Paraíba',
    cep: '58010-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Casa do Tabuleiro - Paraná',
    cep: '85814680',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Jogos do Sul - Paraná',
    cep: '80010-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Meeples do Nordeste - Pernambuco',
    cep: '55038655',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'O Covil do Jogo - Pernambuco',
    cep: '50010-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Jogos e Dados - Piauí',
    cep: '64022-400',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Meeple e Companhia - Piauí',
    cep: '64010-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Desafio do Rio - Rio de Janeiro',
    cep: '94010-280',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Tabuleiro Carioca - Rio de Janeiro',
    cep: '20010-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Meeple Potiguar - Rio Grande do Norte',
    cep: '59612471',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Tabuleiro do Nordeste - Rio Grande do Norte',
    cep: '59010-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Lúdicos do Sul - Rio Grande do Sul',
    cep: '93295540',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Jogos Gaúchos - Rio Grande do Sul',
    cep: '90010-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Reino dos Tabuleiros - Rondônia',
    cep: '76814-064',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Tabuleiro Rondoniense - Rondônia',
    cep: '76961869',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Jogos & Cia - Roraima',
    cep: '69317304',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Desafio Roraima - Roraima',
    cep: '69310-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Tabuleiros do Sul - Santa Catarina',
    cep: '89228710',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Jogos Catarinenses - Santa Catarina',
    cep: '88010-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Império dos Meeples - São Paulo',
    cep: '13058005',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Tabuleiros Paulistas - São Paulo',
    cep: '13341-700',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Tabuleiros Sergipanos - Sergipe',
    cep: '49072-610',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Jogo & Aventura - Sergipe',
    cep: '49010-000',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
  {
    nome: 'Tabuleiros do Tocantins - Tocantins',
    cep: '77804060',
    segmento: 'Jogos de Tabuleiro',
    numero: '1',
  },
  {
    nome: 'Jornada do Tabuleiro - Tocantins',
    cep: '77818-210',
    segmento: 'Jogos de Tabuleiro',
    numero: '2',
  },
];

export default lojas;
